import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { ArrowLeft, Loader2, Maximize2, Minimize2, ExternalLink } from 'lucide-react'

interface GeneratedProject {
  id: string
  project_slug: string
  code_files: Record<string, string> | null
  preview_url: string | null
  build_request: {
    title: string
    short_description: string
  }
}

// Convert React TSX to static HTML (simplified version)
function convertReactToStaticHtml(appContent: string, title: string): string {
  // Try to extract the main return statement from the App component
  const returnMatch = appContent.match(/return\s*\(\s*([\s\S]*?)\s*\)\s*;?\s*\}/m)
  
  if (returnMatch) {
    let jsx = returnMatch[1]
    
    // Convert JSX syntax to HTML
    jsx = jsx
      // Remove className= and convert to class=
      .replace(/className=/g, 'class=')
      // Remove JSX expressions like {variable}
      .replace(/\{[^}]+\}/g, '')
      // Convert self-closing tags
      .replace(/<(\w+)([^>]*)\s*\/>/g, '<$1$2></$1>')
      // Remove React-specific attributes
      .replace(/\s+(onClick|onChange|onSubmit|key|ref)=\{[^}]+\}/g, '')
      // Convert component tags to divs (simplified)
      .replace(/<(Home|Quiz|Results|Header|Footer|[A-Z]\w+)([^>]*)>/g, '<div class="component-$1"$2>')
      .replace(/<\/(Home|Quiz|Results|Header|Footer|[A-Z]\w+)>/g, '</div>')
      // Handle Link components
      .replace(/<Link\s+to="([^"]+)"([^>]*)>/g, '<a href="$1"$2>')
      .replace(/<\/Link>/g, '</a>')
      // Handle icon components (lucide-react)
      .replace(/<(Film|Home|List|BarChart|Check|X|Trophy|User|CheckCircle|XCircle|Facebook|Twitter|Instagram|Sparkles)\s*([^>]*)\/?>/g, 
        '<span class="icon" title="$1">●</span>')
    
    return jsx
  }
  
  // Fallback: Create a nice placeholder
  return `
    <div class="min-h-screen flex flex-col">
      <header class="p-4 bg-zinc-800 shadow-md">
        <div class="container mx-auto flex justify-between items-center">
          <h1 class="text-2xl font-bold">${title}</h1>
          <nav class="flex space-x-4">
            <a href="#" class="hover:text-blue-400 transition">Home</a>
            <a href="#" class="hover:text-blue-400 transition">Features</a>
            <a href="#" class="hover:text-blue-400 transition">About</a>
          </nav>
        </div>
      </header>
      
      <main class="flex-1 flex items-center justify-center p-6">
        <div class="text-center max-w-lg">
          <div class="text-6xl mb-4">🚀</div>
          <h2 class="text-4xl font-bold mb-4 bg-gradient-to-r from-cyan-500 to-purple-600 bg-clip-text text-transparent">
            ${title}
          </h2>
          <p class="text-zinc-400 mb-6">
            This is a preview of your generated project. Download the code to run the full interactive version.
          </p>
          <div class="flex gap-4 justify-center">
            <button class="px-6 py-3 bg-gradient-to-r from-cyan-500 to-purple-600 rounded-lg font-semibold hover:opacity-90 transition">
              Get Started
            </button>
            <button class="px-6 py-3 bg-zinc-800 rounded-lg font-semibold hover:bg-zinc-700 transition">
              Learn More
            </button>
          </div>
        </div>
      </main>
      
      <footer class="p-4 bg-zinc-800 text-center text-zinc-400">
        <p>Generated by BuildLab • ${new Date().getFullYear()}</p>
      </footer>
    </div>
  `
}

// Generate a standalone HTML document that can run in an iframe
function generatePreviewHtml(codeFiles: Record<string, string>, title: string): string {
  // Extract key files
  const indexCss = codeFiles['src/index.css'] || ''
  const appTsx = codeFiles['src/App.tsx'] || codeFiles['src/App.jsx'] || ''
  
  // Convert TSX/JSX to simplified HTML representation
  const previewHtml = convertReactToStaticHtml(appTsx, title)
  
  // Extract Tailwind classes and create inline styles
  const cssContent = `
    /* Base Tailwind-like reset and utilities */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { font-family: Inter, system-ui, -apple-system, sans-serif; line-height: 1.5; }
    body { min-height: 100vh; }
    
    /* Dark theme base */
    .bg-zinc-900, .bg-zinc-950, .bg-slate-900, .bg-slate-950, .bg-gray-900 { background-color: #0a0a0a; }
    .bg-zinc-800, .bg-slate-800 { background-color: #27272a; }
    .bg-zinc-700, .bg-slate-700 { background-color: #3f3f46; }
    .text-white { color: #fff; }
    .text-gray-400, .text-zinc-400, .text-slate-400 { color: #a1a1aa; }
    .text-gray-300, .text-zinc-300 { color: #d4d4d8; }
    
    /* Gradients */
    .bg-gradient-to-b { background: linear-gradient(to bottom, var(--tw-gradient-stops)); }
    .bg-gradient-to-r { background: linear-gradient(to right, var(--tw-gradient-stops)); }
    .from-zinc-900 { --tw-gradient-from: #18181b; --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }
    .via-slate-800 { --tw-gradient-stops: var(--tw-gradient-from), #1e293b, var(--tw-gradient-to, transparent); }
    .to-zinc-900 { --tw-gradient-to: #18181b; }
    .from-purple-500 { --tw-gradient-from: #a855f7; }
    .to-pink-500 { --tw-gradient-to: #ec4899; }
    .from-blue-500 { --tw-gradient-from: #3b82f6; }
    .to-purple-600 { --tw-gradient-to: #9333ea; }
    .from-cyan-500 { --tw-gradient-from: #06b6d4; }
    
    /* Layout */
    .min-h-screen { min-height: 100vh; }
    .flex { display: flex; }
    .flex-col { flex-direction: column; }
    .flex-1 { flex: 1 1 0%; }
    .items-center { align-items: center; }
    .justify-center { justify-content: center; }
    .justify-between { justify-content: space-between; }
    .gap-2 { gap: 0.5rem; }
    .gap-4 { gap: 1rem; }
    .space-x-4 > * + * { margin-left: 1rem; }
    .space-y-3 > * + * { margin-top: 0.75rem; }
    .container { width: 100%; max-width: 1280px; margin: 0 auto; }
    .mx-auto { margin-left: auto; margin-right: auto; }
    .max-w-lg { max-width: 32rem; }
    .max-w-md { max-width: 28rem; }
    
    /* Spacing */
    .p-4 { padding: 1rem; }
    .p-6 { padding: 1.5rem; }
    .px-4 { padding-left: 1rem; padding-right: 1rem; }
    .px-6 { padding-left: 1.5rem; padding-right: 1.5rem; }
    .py-2 { padding-top: 0.5rem; padding-bottom: 0.5rem; }
    .py-3 { padding-top: 0.75rem; padding-bottom: 0.75rem; }
    .py-6 { padding-top: 1.5rem; padding-bottom: 1.5rem; }
    .mb-4 { margin-bottom: 1rem; }
    .mb-6 { margin-bottom: 1.5rem; }
    .mt-4 { margin-top: 1rem; }
    .mt-6 { margin-top: 1.5rem; }
    .mr-2 { margin-right: 0.5rem; }
    .mr-3 { margin-right: 0.75rem; }
    
    /* Typography */
    .text-sm { font-size: 0.875rem; }
    .text-xl { font-size: 1.25rem; }
    .text-2xl { font-size: 1.5rem; }
    .text-3xl { font-size: 1.875rem; }
    .text-4xl { font-size: 2.25rem; }
    .text-6xl { font-size: 3.75rem; }
    .font-bold { font-weight: 700; }
    .font-semibold { font-weight: 600; }
    .text-center { text-align: center; }
    
    /* Effects */
    .shadow-md { box-shadow: 0 4px 6px -1px rgba(0,0,0,.1), 0 2px 4px -1px rgba(0,0,0,.06); }
    .shadow-lg { box-shadow: 0 10px 15px -3px rgba(0,0,0,.1), 0 4px 6px -2px rgba(0,0,0,.05); }
    .rounded-lg { border-radius: 0.5rem; }
    .rounded-full { border-radius: 9999px; }
    
    /* Colors */
    .text-blue-400 { color: #60a5fa; }
    .text-purple-500 { color: #a855f7; }
    .text-green-500 { color: #22c55e; }
    .text-red-500 { color: #ef4444; }
    .text-yellow-500 { color: #eab308; }
    .border-l-4 { border-left-width: 4px; }
    .border-green-500 { border-color: #22c55e; }
    .border-red-500 { border-color: #ef4444; }
    
    /* Hover states */
    .hover\\:bg-zinc-700:hover { background-color: #3f3f46; }
    .hover\\:text-blue-400:hover { color: #60a5fa; }
    .hover\\:text-white:hover { color: #fff; }
    .hover\\:opacity-90:hover { opacity: 0.9; }
    .transition { transition: all 0.15s ease; }
    .transition-colors { transition: color 0.15s ease, background-color 0.15s ease; }
    .cursor-pointer { cursor: pointer; }
    
    /* Gradient text */
    .bg-clip-text { -webkit-background-clip: text; background-clip: text; }
    .text-transparent { color: transparent; }
    
    /* Grid */
    .grid { display: grid; }
    .grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    
    /* Icons placeholder */
    .icon { width: 1.25rem; height: 1.25rem; display: inline-block; vertical-align: middle; }
    
    /* Buttons */
    button { border: none; cursor: pointer; }
    
    /* Custom styles from the project */
    ${indexCss.replace(/@tailwind[^;]+;/g, '').replace(/@layer[^{]+\{[^}]+\}/g, '')}
  `

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - Preview</title>
  <style>${cssContent}</style>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body class="bg-zinc-950 text-white">
  ${previewHtml}
</body>
</html>`
}

export function DemoPage() {
  const { projectSlug } = useParams()
  const [project, setProject] = useState<GeneratedProject | null>(null)
  const [loading, setLoading] = useState(true)
  const [fullscreen, setFullscreen] = useState(false)
  const [iframeContent, setIframeContent] = useState<string>('')

  useEffect(() => {
    const loadProject = async () => {
      if (!projectSlug) return

      const { data, error } = await supabase
        .from('generated_projects')
        .select(`
          id,
          project_slug,
          code_files,
          preview_url,
          build_request:build_requests(title, short_description)
        `)
        .eq('project_slug', projectSlug)
        .single()

      if (error) {
        console.error('Error loading project:', error)
        setLoading(false)
        return
      }

      setProject(data as GeneratedProject)
      
      // Generate the iframe content from code_files
      if (data?.code_files) {
        const html = generatePreviewHtml(
          data.code_files as Record<string, string>, 
          data.build_request?.title || 'Demo'
        )
        setIframeContent(html)
      }
      
      setLoading(false)
    }

    loadProject()
  }, [projectSlug])

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center">
        <Loader2 className="w-8 h-8 text-cyan-400 animate-spin" />
      </div>
    )
  }

  if (!project || !iframeContent) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-white mb-4">Preview Not Available</h1>
          <p className="text-slate-400 mb-6">This project doesn't have a preview yet.</p>
          <Link to={`/project/${projectSlug}`} className="text-cyan-400 hover:underline">
            ← Back to Project
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className={`bg-slate-950 ${fullscreen ? 'fixed inset-0 z-50' : 'min-h-screen'}`}>
      {/* Header Bar */}
      <div className="bg-slate-900 border-b border-slate-800 px-4 py-2 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link 
            to={`/project/${projectSlug}`}
            className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors"
          >
            <ArrowLeft size={18} />
            <span>Back to Project</span>
          </Link>
          <div className="h-4 w-px bg-slate-700" />
          <span className="text-white font-medium">{project.build_request?.title}</span>
          <span className="px-2 py-0.5 bg-cyan-500/20 text-cyan-400 text-xs rounded">Preview</span>
        </div>
        
        <div className="flex items-center gap-2">
          {project.preview_url && (
            <a
              href={project.preview_url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 px-3 py-1.5 text-sm text-slate-400 hover:text-white transition-colors"
            >
              <ExternalLink size={16} />
              <span>Open External</span>
            </a>
          )}
          <button
            onClick={() => setFullscreen(!fullscreen)}
            className="flex items-center gap-2 px-3 py-1.5 text-sm bg-slate-800 hover:bg-slate-700 text-white rounded transition-colors"
          >
            {fullscreen ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
            <span>{fullscreen ? 'Exit Fullscreen' : 'Fullscreen'}</span>
          </button>
        </div>
      </div>

      {/* Preview Frame */}
      <div className={`${fullscreen ? 'h-[calc(100vh-49px)]' : 'h-[calc(100vh-120px)]'}`}>
        <iframe
          srcDoc={iframeContent}
          title={`${project.build_request?.title} Preview`}
          className="w-full h-full border-0"
          sandbox="allow-scripts allow-same-origin"
        />
      </div>
    </div>
  )
}
