// BuildLab Project Generator - Multi-Agent AI System
// This Edge Function orchestrates AI agents to generate complete project packages

import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0'

const supabaseUrl = Deno.env.get('SUPABASE_URL')!
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const openaiKey = Deno.env.get('OPENAI_API_KEY')!
const githubToken = Deno.env.get('GITHUB_TOKEN')!

interface ProjectRequest {
  build_request_id: string
  user_id: string
  title: string
  description: string
  category: string
  target_audience: string
  features: string[]
}

interface GeneratedProject {
  charter: string
  market_research: string
  prd: string
  tech_spec: string
  code_files: Record<string, string>
  preview_url: string
  github_url: string
}

// Agent prompts for specialized tasks
const AGENT_PROMPTS = {
  research: `You are a Senior Market Research Analyst. Analyze the following project idea and provide:
1. Market size and opportunity
2. Top 5 competitors with strengths/weaknesses
3. Target audience personas (3)
4. Unique value proposition recommendations
5. Go-to-market strategy suggestions

Be specific, cite realistic data, and provide actionable insights.`,

  product_manager: `You are a Senior Product Manager at a top tech company. Create a comprehensive PRD including:
1. Executive Summary
2. Problem Statement
3. Goals and Success Metrics
4. User Stories (at least 10 with acceptance criteria)
5. MVP Feature Set (prioritized)
6. Out of Scope items
7. Timeline estimate
8. Risks and Mitigations

Format in clean Markdown.`,

  architect: `You are a Principal Software Architect. Design the technical architecture including:
1. System Overview Diagram (describe in text)
2. Technology Stack Recommendations with justifications
3. Database Schema (with relationships)
4. API Endpoints (RESTful design)
5. Authentication & Authorization approach
6. Scalability considerations
7. Third-party integrations needed

Be specific and practical for an MVP.`,

  project_charter: `You are a Project Management Professional. Create a formal Project Charter including:
1. Project Title and Description
2. Business Case and Justification
3. Project Objectives (SMART goals)
4. Scope Statement (In/Out of scope)
5. Key Stakeholders
6. High-level Requirements
7. Assumptions and Constraints
8. Preliminary Budget Estimate
9. Key Milestones
10. Success Criteria

Format professionally in Markdown.`,

  coder: `You are an Expert Full-Stack Developer specializing in React, TypeScript, and Tailwind CSS.
Generate a complete, working MVP based on the provided specifications.

Requirements:
- Use React 18 with TypeScript
- Use Tailwind CSS for styling (dark theme, modern UI)
- Create realistic mock data
- Include responsive design
- Add loading states and error handling
- Use Lucide React for icons
- Make it visually impressive

Return a JSON object with file paths as keys and file contents as values.
Include: package.json, index.html, src/main.tsx, src/App.tsx, src/index.css, and all component files.`
}

// Call OpenAI API
async function callAgent(systemPrompt: string, userPrompt: string, isJson = false): Promise<string> {
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${openaiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'gpt-4o',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature: 0.7,
      max_tokens: 4000,
      ...(isJson && { response_format: { type: 'json_object' } })
    }),
  })

  const data = await response.json()
  return data.choices[0].message.content
}

// Create GitHub repository
async function createGitHubRepo(
  username: string,
  projectSlug: string,
  files: Record<string, string>,
  description: string
): Promise<string> {
  const repoName = `buildlab-${projectSlug}`
  
  // Create repo using GitHub API
  const createRepoResponse = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${githubToken}`,
      'Content-Type': 'application/json',
      'Accept': 'application/vnd.github.v3+json',
    },
    body: JSON.stringify({
      name: repoName,
      description: `${description} - Generated by BuildLab`,
      private: false,
      auto_init: true,
    }),
  })

  if (!createRepoResponse.ok) {
    const error = await createRepoResponse.text()
    console.error('GitHub repo creation failed:', error)
    throw new Error('Failed to create GitHub repository')
  }

  const repo = await createRepoResponse.json()
  
  // Add files to repo
  for (const [path, content] of Object.entries(files)) {
    await fetch(`https://api.github.com/repos/${repo.full_name}/contents/${path}`, {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${githubToken}`,
        'Content-Type': 'application/json',
        'Accept': 'application/vnd.github.v3+json',
      },
      body: JSON.stringify({
        message: `Add ${path}`,
        content: btoa(unescape(encodeURIComponent(content))),
      }),
    })
  }

  return repo.html_url
}

// Main handler
Deno.serve(async (req) => {
  // Handle CORS
  if (req.method === 'OPTIONS') {
    return new Response(null, {
      status: 204,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      },
    })
  }

  try {
    const supabase = createClient(supabaseUrl, supabaseServiceKey)
    
    // Get request body
    const { build_request_id } = await req.json()
    
    // Fetch build request details
    const { data: buildRequest, error: fetchError } = await supabase
      .from('build_requests')
      .select('*, profiles(*)')
      .eq('id', build_request_id)
      .single()

    if (fetchError || !buildRequest) {
      throw new Error('Build request not found')
    }

    const projectContext = `
Project Title: ${buildRequest.title}
Category: ${buildRequest.category}
Description: ${buildRequest.description}
Short Description: ${buildRequest.short_description}
Target Audience: ${buildRequest.target_audience || 'General users'}
Key Features Requested: ${buildRequest.features?.join(', ') || 'Standard web application features'}
Creator: ${buildRequest.profiles?.username}
    `.trim()

    // Update status to processing
    await supabase
      .from('build_requests')
      .update({ generation_status: 'processing' })
      .eq('id', build_request_id)

    console.log('🚀 Starting multi-agent project generation...')

    // Run agents in parallel where possible
    const [marketResearch, projectCharter] = await Promise.all([
      callAgent(AGENT_PROMPTS.research, projectContext),
      callAgent(AGENT_PROMPTS.project_charter, projectContext),
    ])

    console.log('✅ Research & Charter complete')

    // PRD needs research context
    const prdContext = `${projectContext}\n\nMarket Research:\n${marketResearch}`
    const prd = await callAgent(AGENT_PROMPTS.product_manager, prdContext)

    console.log('✅ PRD complete')

    // Tech spec needs PRD context
    const techContext = `${projectContext}\n\nPRD:\n${prd}`
    const techSpec = await callAgent(AGENT_PROMPTS.architect, techContext)

    console.log('✅ Tech Spec complete')

    // Code generation needs all context
    const codeContext = `
${projectContext}

PRD Summary:
${prd.substring(0, 2000)}

Technical Spec:
${techSpec}

Generate a complete, working React application based on these specifications.
Make it visually impressive with a modern dark theme, animations, and professional UI.
Include realistic mock data and full interactivity.
    `.trim()

    const codeFilesJson = await callAgent(AGENT_PROMPTS.coder, codeContext, true)
    const codeFiles = JSON.parse(codeFilesJson)

    console.log('✅ Code generation complete')

    // Generate project slug
    const projectSlug = buildRequest.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .substring(0, 30)

    // Create GitHub repo
    let githubUrl = ''
    try {
      githubUrl = await createGitHubRepo(
        buildRequest.profiles?.username || 'user',
        projectSlug,
        codeFiles,
        buildRequest.short_description
      )
      console.log('✅ GitHub repo created:', githubUrl)
    } catch (e) {
      console.error('GitHub creation failed, continuing...', e)
    }

    // Generate preview URL (would be deployed to your hosting platform)
    const previewUrl = `https://preview.buildlab.app/${projectSlug}`

    // Store generated content
    const { error: insertError } = await supabase
      .from('generated_projects')
      .upsert({
        build_request_id,
        user_id: buildRequest.user_id,
        project_slug: projectSlug,
        market_research: marketResearch,
        project_charter: projectCharter,
        prd,
        tech_spec: techSpec,
        code_files: codeFiles,
        preview_url: previewUrl,
        github_url: githubUrl,
        status: 'completed',
        generated_at: new Date().toISOString(),
      })

    if (insertError) {
      console.error('Failed to save generated project:', insertError)
    }

    // Update build request status
    await supabase
      .from('build_requests')
      .update({ 
        generation_status: 'completed',
        preview_url: previewUrl,
        github_url: githubUrl,
      })
      .eq('id', build_request_id)

    console.log('🎉 Project generation complete!')

    return new Response(
      JSON.stringify({
        success: true,
        project: {
          preview_url: previewUrl,
          github_url: githubUrl,
          documents: {
            market_research: marketResearch.substring(0, 500) + '...',
            project_charter: projectCharter.substring(0, 500) + '...',
            prd: prd.substring(0, 500) + '...',
            tech_spec: techSpec.substring(0, 500) + '...',
          }
        }
      }),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
      }
    )

  } catch (error) {
    console.error('Project generation error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
      }
    )
  }
})
